version: "3.3"

services:
  stored-procedures-mysql:
    container_name: ${CONTAINER_NAME}
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - db_shared
    volumes:
      - "./db:/var/lib/mysql"
      - "./dump:/docker-entrypoint-initdb.d"
    ports:
      - 9306:3306

networks:
  db_shared:
    driver: bridge
